input = [energy_threshold_arca : 1e2,
         energy_low_arca : 2,
         energy_high_arca : 8,
         trackscore_threshold_arca : 0.3,
         muonscore_threshold_arca : 0.5,
         energy_threshold_orca : 1e-2,
         energy_low_orca : 0,
         energy_high_orca : 2,
         trackscore_threshold_orca : 0.3,
         muonscore_threshold_orca : 0.5,
         bins_per_file  : 200,
         pulseshape : "mvm",
         frequency : 11,
         inject_method : 'base',  
         df : 1e-5,
         testf_df: 5e-4,
         ratio_min : 0.001, // Lower limit of the ratio
         ratio_max : 0.5, // Upper limit of the ratio
         ratio_step : 0.025, // Step for the ratio
         repetitions : 25, // Number of repetitions for each ratio
         number_of_testf : 1000,
         nbin : 32,
         kappa : 5.0,
         a : 1.0,
         baseline : 0.0,
         phi : 0.0,
         nhbins : 8,
         source_file : "${WORKFLOW_DIR}/inputs/sources/Vela_X-1.h5",
	     km3net_arca_numu_files : "${WORKFLOW_DIR}/inputs/arca_runs_numu_test.txt",
         km3net_arca_anue_files : "${WORKFLOW_DIR}/inputs/arca_runs_anue_test.txt",
         km3net_arca_data_files : "${WORKFLOW_DIR}/../data_files_arca_v9_trackscore.txt", 
         km3net_arca_mc_files : "${WORKFLOW_DIR}/../mc_files_arcav9.txt", 
         km3net_orca_numu_files : "${WORKFLOW_DIR}/inputs/orca_runs_numu_test.txt",
         km3net_orca_anue_files : "${WORKFLOW_DIR}/inputs/orca_runs_anue_test.txt",
         km3net_orca_data_files : "${WORKFLOW_DIR}/../data_files_orca.txt", 
         km3net_orca_mc_files : "${WORKFLOW_DIR}/../mc_files_orcav9.txt", 
         ar_shower_file_arca : "${WORKFLOW_DIR}/inputs/angular_res_files/AngularResolutionOverEnergy_aashower_mcv8.1.gsg_anue-CCHEDIS_1e2-1e8GeV.sirene.jterbr00013.hdf5",
         ar_track_file_arca : "${WORKFLOW_DIR}/inputs/angular_res_files/AngularResolutionOverEnergy_jmuon_mcv8.1.gsg_numu-CCHEDIS_1e2-1e8GeV.sirene.jterbr000132.hdf5",
         ar_shower_file_orca : "${WORKFLOW_DIR}/inputs/angular_res_files/AngularResolutionOverEnergy_jshower_gsg_elec-CC_1.0-100.0GeV_orca.hdf5",
         ar_track_file_orca : "${WORKFLOW_DIR}/inputs/angular_res_files/AngularResolutionOverEnergy_jmuon_gsg_muon-CC_1.0-100.0GeV_orca.hdf5",
         delta_search_min : 5.0,
         folding_segment_size : 1e11,
         // parampid_folder : "/home/hpc/capn/capn107h/software/nextflow_output/parampid/classified_files",
         parampid_folder : "/home/wecapstor3/capn/capn107h/classified_files",
         weights_folder : "/home/hpc/capn/capn107h/software/nextflow_output/weights",
         // weights_folder : "/home/wecapstor3/capn/capn107h/atm_weight_files",
         orca_weights_file : "/home/wecapstor3/capn/capn107h/atm_weight_files/KM3NeT_00000148_00016602.mc.gsg_neutrinos.km3sim_sirene_merged.jterbr.jppmuon_jppshower_static.offline.v9.2_atm_neutrino_weights.hdf5",
         arca_weights_file : "/home/wecapstor3/capn/capn107h/atm_weight_files/KM3NeT_00000133_00017633.mc.gsg_astro-neutrinos_merged.sirene.jterbr.jppmuon_aashower_static.offline.v9.0_atm_neutrino_weights.hdf5",
         // orca_weights_file : "/home/wecapstor3/capn/capn107h/atm_weight_files/KM3NeT_00000148_00016716.mc.gsg_neutrinos.km3sim_sirene_merged.jterbr.jppmuon_jppshower_static.offline.v9.2_atm_neutrino_weights.hdf5",
         // arca_weights_file : "/home/wecapstor3/capn/capn107h/atm_weight_files/mcv8.1.gsg_numu-CCHEDIS_1e2-1e8GeV.sirene.jterbr00013329.jchain.aashower.40_atm_neutrino_weights.hdf5"
         // orca_weights_file : "/home/hpc/capn/capn107h/software/nextflow_output/weights/KM3NeT_00000148_00016602.mc.gsg_neutrinos.km3sim_sirene_merged.jterbr.jppmuon_jppshower_static.offline.v9.2_atm_neutrino_weights.hdf5",
         // arca_weights_file : "/home/hpc/capn/capn107h/software/nextflow_output/weights/KM3NeT_00000133_00017633.mc.gsg_astro-neutrinos_merged.sirene.jterbr.jppmuon_aashower_static.offline.v9.0_atm_neutrino_weights.hdf5",
         // gti_file : "/home/hpc/capn/capn107h/software/psr/workflows/km3net/km3net_analysis/orca__combined_eventlist_18393events_gtis.hdf5.pkl",
         gti_file : "/home/hpc/capn/capn107h/software/psr/workflows/km3net/km3net_analysis/gtifile_combined_gtis.pkl",
         filestype : "data",
         detector : "arcaorca",
         cone_all : "False",
         plot_all : 'False',
         corrected_eventlist : "/home/wecapstor3/capn/capn107h/corrected_files/arca_KM3NeT_00000133_0001_combined_7923events_corrected.hdf5",
         convert : 'False',
         add_trackscore : 'False',
         arca_energy_response_file : "/home/wecapstor3/capn/capn107h/energy_response_files/arca_energy_response_histogram.hdf5"
         ]

         // /home/hpc/capn/capn107h/software/psr/workflows/km3net/km3net_sensitivity/inputs/runs.txt